# Generated by Django 4.2.10 on 2024-02-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_building_is_active_alter_company_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
