# Generated by Django 4.2.10 on 2024-02-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_building_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='office',
            unique_together={('building', 'floor', 'number')},
        ),
    ]
