# Generated by Django 4.2.10 on 2024-02-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_office_options_alter_office_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['created']},
        ),
        migrations.AlterUniqueTogether(
            name='office',
            unique_together=set(),
        ),
    ]
