# Generated by Django 4.2.10 on 2024-02-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_office_options_alter_office_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useroffice',
            old_name='Office',
            new_name='office',
        ),
    ]
